FROM node:latest


RUN npm install -g bower
RUN npm install -g yarn
COPY ./package.json /package.json
COPY ./bower.json /bower.json
RUN bower install --allow-root
RUN npm install yarn
RUN ./node_modules/.bin/yarn
